name: Generate workflow files to make issue
on:
  workflow_dispatch:
  schedule:
  - cron: '0 19 * * *'  # At 04:00. – https://crontab.guru

jobs:
  generate_workflows:
    name: Generate workflow files
    runs-on: ubuntu-latest
    steps:

    # Repo code checkout required if `template` is used
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ISSUEBOT_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        architecture: 'x64'
    
    - name: Get Python version
      run: python -V
    
    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt
      working-directory: ./generateIssueWf
      
    - name: Run Python
      run: python generate_workflow_to_make_issue.py
      working-directory: ./generateIssueWf

    - name: git setting
      run: |
        git config --local user.email "52403447+landmaster135@users.noreply.github.com"
        git config --local user.name "landmaster135"
    
    - name: git commit
      run: |
        git log -1
        git add .github/workflows/generateIssues_*.yml
        git add .github/workflows/generatedWfFiles.txt
        git add .github/workflows/removeWfForIssuesAndCsvContent.yml
        git diff --cached --quiet || (git commit -m "Generate workflow to make issues" && git push origin master)
